version: '3'

services:
  git:
    container_name: git
    build: ./docker/git
    volumes:
      - $HOME/git:/git:delegated
      - $HOME/.netrc:/root/.netrc:ro
      - $HOME/.gitconfig:/root/.gitconfig:rw
